language: python

# using container based testing is faster, but you can't use sudo
sudo: false

python:
    - "2.7_with_system_site_packages"
    # - "2.7"

env:
    global:
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/save/lib
        - PYTHONPATH=$PYTHONPATH:$HOME/save/lib:$HOME/save/lib/python2.7:$HOME/save/lib/python2.7/site-packages

# command to install dependencies that require sudo
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        packages:
            # - libopencv-dev
            # - python-opencv
            - python-numpy
            # - python-scipy
            # - libdc1394-22-dev
            # - libdc1394-utils
            - python-yaml
            - build-essential
            - cmake
            - libgtk2.0-dev
            - pkg-config
            - libavcodec-dev
            - libavformat-dev
            - libswscale-dev
            - python-dev
            - python-numpy
            - libtbb2
            - libtbb-dev
            - libjpeg-dev
            - libpng-dev
            - libtiff-dev
            - libjasper-dev
            - ffmpeg

cache:
    directories:
        - $HOME/save

before_install:
    - ./install-opencv.sh

# install other libraries using pip
install:
    - pip install -U pip setuptools wheel
    - pip install .
    # - pip install -U matplotlib nose

# command to run tests
script: nosetests -v tests/test.py
